<a href="https://colab.research.google.com/github/Ying038/WIA1007/blob/main/Tutorial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
# Question 1
array1 = np.array([[1,2],[3,4]])
print (array1)

[[1 2]
 [3 4]]


In [ ]:
# Question 2
array2 = np.random.rand(3,4)
print (array2)

[[0.69227518 0.43769209 0.81044009 0.59798473]
 [0.23969928 0.25964982 0.46631848 0.5246586 ]
 [0.19427356 0.7795747  0.18313751 0.00727852]]


In [ ]:
# Question 3
arrayOfOnes = np.ones((3,3))
print(arrayOfOnes)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
arrayOfZeroes = np.zeros((3,3))
print(arrayOfZeroes)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
# Question 4
array3 = np.random.rand(6,3)
print(array3)

[[0.79631165 0.1826472  0.2954511 ]
 [0.46344413 0.83659903 0.25231712]
 [0.19512974 0.39948945 0.81576122]
 [0.75175129 0.5258257  0.59574194]
 [0.52214319 0.10804925 0.84822859]
 [0.06407286 0.30319294 0.90755556]]


In [5]:
transposedArray3 = array3.T
print(transposedArray3)

[[0.79631165 0.46344413 0.19512974 0.75175129 0.52214319 0.06407286]
 [0.1826472  0.83659903 0.39948945 0.5258257  0.10804925 0.30319294]
 [0.2954511  0.25231712 0.81576122 0.59574194 0.84822859 0.90755556]]


In [6]:
# Question 5
arrayA = np.random.rand(2,3)
print(arrayA)

[[0.98504869 0.28968441 0.07790872]
 [0.59865074 0.45340215 0.35656691]]


In [7]:
arrayB = np.random.rand(3,4)
print(arrayB)

[[0.68534309 0.2019619  0.25399951 0.17989142]
 [0.7305643  0.16423629 0.35826131 0.80237679]
 [0.45707659 0.31974488 0.25035071 0.6193684 ]]


In [8]:
dotProduct = np.dot(arrayA,arrayB)
print(dotProduct)

[[0.92233965 0.27142991 0.37348911 0.45789205]
 [0.90449896 0.30938017 0.40376022 0.69233777]]
