WIA1007 Tutorial 3

In [1]:
import numpy as np

1. Create a numpy array of size 2 x 2

In [2]:
# Question 1
array1 = np.array([[1,2],[3,4]])
print("2x2 Array:")
print(array1)

2x2 Array:
[[1 2]
 [3 4]]


2. Create a random numpy array of size 3 x 4

In [3]:
# Question 2
array2 = np.random.random((3,4))
print("Random 3x4 Array:")
print(array2)

Random 3x4 Array:
[[0.93742213 0.72998605 0.86405167 0.98736581]
 [0.31678091 0.8676326  0.78890673 0.08939598]
 [0.50609418 0.40398791 0.27194894 0.05052863]]


3. Create a numpy array of ones and a numpy array of zeroes

In [4]:
# Question 3
arrayOfOnes = np.ones((3,3))
print("Array of Ones:")
print(arrayOfOnes)

Array of Ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
arrayOfZeroes = np.zeros((3,3))
print("Array of Zeroes:")
print(arrayOfZeroes)

Array of Zeroes:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


4. Create a random numpy array of size 6x3 and transpose it

In [6]:
# Question 4
array3 = np.random.random((6,3))
print("Original random 6x3 Array:")
print(array3)

Original random 6x3 Array:
[[0.93628983 0.39438059 0.78979382]
 [0.37214698 0.98594436 0.3970012 ]
 [0.48972835 0.32873253 0.3002144 ]
 [0.28356257 0.31572591 0.76585317]
 [0.84202987 0.39166905 0.81767339]
 [0.03376774 0.57387549 0.32452232]]


In [7]:
transposedArray3 = array3.T
print("Transposed Array:")
print(transposedArray3)

Transposed Array:
[[0.93628983 0.37214698 0.48972835 0.28356257 0.84202987 0.03376774]
 [0.39438059 0.98594436 0.32873253 0.31572591 0.39166905 0.57387549]
 [0.78979382 0.3970012  0.3002144  0.76585317 0.81767339 0.32452232]]


5. Create two random numpy array of size n x p and p x m and then compute the dot product

In [8]:
# Question 5
n = 2
p = 3
m = 4
arrayA = np.random.random((n,p))
print("Array A (n x p):")
print(arrayA)

Array A (n x p):
[[0.71006167 0.25704115 0.90053306]
 [0.6353265  0.47634865 0.90853396]]


In [9]:
arrayB = np.random.random((p,m))
print("Array B (p x m):")
print(arrayB)

Array B (p x m):
[[0.51468416 0.30752441 0.40263096 0.5676545 ]
 [0.01463878 0.92326474 0.82863581 0.04908446]
 [0.47193438 0.48480088 0.49334203 0.89350542]]


In [10]:
dotProduct = np.dot(arrayA,arrayB)
print("Dot Product:")
print(dotProduct)

Dot Product:
[[0.79421278 0.89225754 0.94315712 1.2203176 ]
 [0.76273406 1.07563238 1.09873966 1.19580728]]
