In [1]:
import numpy as np

In [2]:
# Question 1
array1 = np.array([[1,2],[3,4]])
print (array1)

[[1 2]
 [3 4]]


In [3]:
# Question 2
array2 = np.random.rand(3,4)
print (array2)

[[0.3860346  0.17184417 0.68363236 0.51110849]
 [0.31069292 0.22273097 0.05573521 0.74618699]
 [0.04475628 0.12648168 0.74413367 0.90756256]]


In [4]:
# Question 3
arrayOfOnes = np.ones((3,3))
print(arrayOfOnes)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
arrayOfZeroes = np.zeros((3,3))
print(arrayOfZeroes)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Question 4
array3 = np.random.rand(6,3)
print(array3)

[[0.85993638 0.30534277 0.30036417]
 [0.81594976 0.61479159 0.55427871]
 [0.12818384 0.61460263 0.47335827]
 [0.05690471 0.19041366 0.59709857]
 [0.90673055 0.79530925 0.18755813]
 [0.54862607 0.91937501 0.93225522]]


In [7]:
transposedArray3 = array3.T
print(transposedArray3)

[[0.85993638 0.81594976 0.12818384 0.05690471 0.90673055 0.54862607]
 [0.30534277 0.61479159 0.61460263 0.19041366 0.79530925 0.91937501]
 [0.30036417 0.55427871 0.47335827 0.59709857 0.18755813 0.93225522]]


In [8]:
# Question 5
arrayA = np.random.rand(2,3)
print(arrayA)

[[0.37108785 0.83469994 0.35826698]
 [0.27645808 0.8543897  0.83094146]]


In [9]:
arrayB = np.random.rand(3,4)
print(arrayB)

[[0.2146983  0.61805085 0.07106233 0.25893535]
 [0.71349578 0.11136031 0.74544504 0.68744535]
 [0.77198479 0.86711773 0.32672623 0.59371314]]


In [10]:
dotProduct = np.dot(arrayA,arrayB)
print(dotProduct)

[[0.95180347 0.63296325 0.76564852 0.88260617]
 [1.31043269 0.98653431 0.92803669 1.15227186]]
